name: ğŸ—ï¸ Deploy to zero

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ğŸ—ï¸ Deploying to zero ...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ZERO_HOST }}
          username: ${{ secrets.ZERO_USERNAME }}
          key: ${{ secrets.ZERO_SSH_KEY }}
          port: 1330
          script: |
            cd /home/snackk/Downloads
            rm -rf wol-web-server
            git clone https://github.com/snackk/wol-web-server.git
            sudo systemctl restart app.service
            sudo systemctl status app.service
